#version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: Mealie
    labels:
      io.portainer.accesscontrol.users: admin
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - mealie-data:/app/data/
    networks:
      - mealie-network
      - mealiedb-network
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
#      - BASE_URL=http://localhost:9000
      - BASE_URL_FILE=/run/secrets/BASE_URL
      - SMTP_HOST_FILE=/run/secrets/SMTP_HOST
      - SMTP_PORT_FILE=/run/secrets/SMTP_PORT
      - SMTP_FROM_NAME=Mealie
      - SMTP_AUTH_STRATEGY_FILE=/run/secrets/SMTP_AUTH_STRATEGY
      - SMTP_FROM_EMAIL_FILE=/run/secrets/SMTP_FROM_EMAIL
      - SMTP_USER_FILE=/run/secrets/SMTP_USER
      - SMTP_PASSWORD_FILE=/run/secrets/SMTP_PASSWORD
    # Database Settings
      - DB_ENGINE=postgres
#      - POSTGRES_USER=mealie
#      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=postgres
#      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    secrets:
      - BASE_URL
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_AUTH_STRATEGY
      - SMTP_FROM_EMAIL
      - SMTP_USER
      - SMTP_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    restart: unless-stopped

  postgres:
    container_name: Postgres
    image: postgres:15
    restart: unless-stopped
    labels:
      io.portainer.accesscontrol.users: admin
    volumes:
      - ${HOME}/.mealie/mealie-pgdata:/var/lib/postgresql/data
    networks:
      - mealiedb-network
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mealie-data:
    driver: local
  mealie-pgdata:
    driver: local

networks:
  mealie-network:
    name: mealie-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mealie-bridge
  mealiedb-network:
    name: mealiedb-network
    driver: bridge
    internal: true

secrets:
  BASE_URL:
    file: ${HOME}/.mealie/secrets/base-url.txt
  POSTGRES_USER:
    file: ${HOME}/.mealie/secrets/postgres-user.txt
  POSTGRES_PASSWORD:
    file: ${HOME}/.mealie/secrets/postgres-password.txt
  POSTGRES_PORT:
    file: ${HOME}/.mealie/secrets/postgres-port.txt
  SMTP_HOST:
    file: ${HOME}/.mealie/secrets/smtp-host.txt
  SMTP_PORT:
    file: ${HOME}/.mealie/secrets/smtp-port.txt
  SMTP_AUTH_STRATEGY:
    file: ${HOME}/.mealie/secrets/smtp-auth-strategy.txt
  SMTP_FROM_EMAIL:
    file: ${HOME}/.mealie/secrets/smtp-from-email.txt
  SMTP_USER:
    file: ${HOME}/.mealie/secrets/smtp-user.txt
  SMTP_PASSWORD:
    file: ${HOME}/.mealie/secrets/smtp-password.txt
