services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - ${HOME}/.linkwarden/.env
    restart: unless-stopped
    volumes:
      - ${HOME}/.linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    container_name: Linkwarden
    #hostname: "Raspberry Pi 4"
    env_file:
      - ${HOME}/.linkwarden/.env
    #environment:
    #  - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: unless-stopped
    # build: . # uncomment to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    ports:
      - 3031:3000
    volumes:
      - ${HOME}/.linkwarden/data:/data/data
    depends_on:
      - postgres
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: unless-stopped
    env_file:
      - ${HOME}/.linkwarden/.env
    volumes:
      - ${HOME}/.linkwarden/meili_data:/meili_data
