services:
  nginx-proxy-manager:
    container_name: NGINX-Proxy-Manager
    #hostname: "Raspberry Pi 4"
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: 'false'
    volumes:
      - ${HOME}/.nginx/data:/data
      - ${HOME}/.nginx/letsencrypt:/etc/letsencrypt
